### ISSUE TITLE
positionOffset: int32 and untiSI

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-viewer#103]
When trying to read a PIConGPU file with the current `dev` branch as of 135809c145c0e70f3d495ce1d612df8633897b7e reading the position via
```python
y,x = ts.get_particle( var_list=['y','x'], t=0, species='e', plot=True, nbins=300, vmax=5e7)
```
leads to:
```
openPMD-viewer/opmd_viewer/openpmd_timeseries/main.pyc in get_particle(self, var_list, species, t, iteration, select, output, plot, nbins, **kw)
    239         for quantity in var_list:
    240             data_list.append(read_species_data(
--> 241                 file_handle, species, quantity, self.extensions))
    242         # Apply selection if needed
    243         if select is not None:

openPMD-viewer/opmd_viewer/openpmd_timeseries/data_reader/particle_reader.pyc in read_species_data(file_handle, species, record_comp, extensions)
     72     # - Return positions in microns, with an offset
     73     if record_comp in ['x', 'y', 'z']:
---> 74         offset = get_data(species_grp['positionOffset/%s' % record_comp])
     75         data += offset
     76         data *= 1.e6

/openPMD-viewer/opmd_viewer/openpmd_timeseries/data_reader/utilities.pyc in get_data(dset, i_slice, pos_slice)
     92     # Scale by the conversion factor
     93     if dset.attrs['unitSI'] != 1.0:
---> 94         data *= dset.attrs['unitSI']
     95 
     96     return(data)

TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
```

That is likely do to the recent changes in #81 #85 and caused by our internal storage of `positionOffset` as an `int32` :)

The result of `positionOffset[()]` (int32) and `unitSI` (float64) should of cause be promoted to `float64` if `unitSI` != `1.0`. Since `*=` is an [in place operation](http://docs.scipy.org/doc/numpy-dev/user/quickstart.html#basic-operations) we can just add a reallocation & cast beforehand if necessary:
```python
if dset.attrs['unitSI'] != 1.0:
    if data.dtype != np.float64:
        data = data.astype(np.float64)
    data *= dset.attrs['unitSI']
```

In recent versions of numpy there is also a [`copy=False` flag](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html): [see this answer](http://stackoverflow.com/questions/4389517/in-place-type-conversion-of-a-numpy-array/10622758#10622758). Note: `view()` will only work if the two casted types are the same `size` in byte.

**Comment by RemiLehe** [comment]
@ax3l : Could you send me one of the HDF5 files produced by PIConGPU (and which produces the above error), so that I can fix the bug and test the fix?
Thanks a lot!

**Comment by RemiLehe** [comment]
PR #113 should fix this issue.

**Comment by ax3l** [comment]
fixed! :) thank you Rémi!

**Comment by RemiLehe** [comment]
Thanks for reviewing and checking the files :)

**Comment by ax3l** [comment]
I think we are good to go now! :)

**Comment by ax3l** [comment]
thank you for fixing that, wuhu!

**Comment by RemiLehe** [comment]
Ok, I'll go for the pypi release now.
