### ISSUE TITLE
Problem with Travis CI

### ISSUE THREAD

**Issue by soerenjalas** [openPMD/openPMD-viewer#107]
Hi,
is there a problem with our continuous integration. It seems that the tests on all PR are on hold and they don't show up on https://travis-ci.org/openPMD/openPMD-viewer.

**Comment by ax3l** [comment]
there was an issue with the service yesterday, lets try to restart the jobs

**Comment by ax3l** [comment]
ok the webhooks could not be delivered. just update the branches to trigger them again.

**Comment by RemiLehe** [comment]
I am updating them now, which is solving the issue.
This was indeed due to an error on Github yesterday.
