### ISSUE TITLE
Add the resolution (e.g. dx, dz) to the FieldMetaInformation object

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-viewer#110]
It would be good if the user can extract the resolution easily.

**Comment by soerenjalas** [comment]
This should be fairly easy to implement, as `grid_spacing` is already passed to the object, right?

So the only thing to add would be something like


```Python
for axis in sorted(axes.keys()):
            # Create the coordinates along this axis 
            step = grid_spacing[axis]*grid_unitSI
            axis_name = axes[axis]
            setattr( self, 'd'+axis_name, step ) # Only line to be added
```

And it wouldn't even compromise older versions of the API. 
A might be missing something, but if you are OK with this approach I can prepare a PR.

**Comment by RemiLehe** [comment]
Yes, this is exactly what I meant (btw, the docstring of the object should be modified accordingly)
If you have time to do the PR, it would be great !
