### ISSUE TITLE
Add fit to get_main_frequency 

### ISSUE THREAD

**Issue by soerenjalas** [openPMD/openPMD-viewer#115]
Currently the method `get_main_frequency` in `LpaDiagnostics` simply searches for the maximum in the FFT. This produces quite unusable data when studying e.g. the redshift of the pulse in plasma. As you can see below the value changes quite unsteadily.
![freq](https://cloud.githubusercontent.com/assets/10922951/16520241/28fd918c-3f8f-11e6-8219-75fdb9840e94.png)

I think by fitting the spectrum one could probably get better results as more data is taken into account.
The question is if a Gaussian fit is sufficient for this purpose as the pulse can change quite violently or people might use exotic pulses. I can work out a PR so we could test if this method gives better results. @RemiLehe any thoughts on this?

**Comment by RemiLehe** [comment]
OK, I see your point. I think fitting a Gaussian is fine, since for a Gaussian laser the spectrum is indeed a Gaussian (at least before significant pulse evolution). As for the other methods, it would be good to give the user the possibility to still use the maximum of the spectrum if they wish.

**Comment by soerenjalas** [comment]
Closed in #116
