### ISSUE TITLE
Add particle tracker in openPMD-viewer

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-viewer#137]
For one of the sets of simulations that I am currently doing, I would need to be able to track particles in postprocessing. 

Assuming that the `id` of the particles have been stored in the openPMD data, then this should be possible with openPMD-viewer, if we add this feature. 

I would definitely volunteer for this, but I would like us to first agree on the API. I thought about introducing a `ParticleTracker` object. This object would be used in the following way, for instance in order to select electrons having a longitudinal momentum between 10 and 100 at iteration 2000, and then fetching the positions of these electrons at iteration 30000 and 50000.
```python
ts = OpenPMDTimeSeries( 'some/directory' )

# Select particles at iteration 2000
pt = ParticleTracker( ts, species='electrons', select={'uz':[10,100]}, iteration=2000 )

# Fetch them at iteration 30000 and 50000
x1, y1, z1 = ts.get_particle( ['x', 'y', 'z'], particle_tracker=pt, iteration=30000 )
x2, y2, z2 = ts.get_particle( ['x', 'y', 'z'], particle_tracker=pt, iteration=50000 )
```
Also, in this case x1, y1, etc. would be arrays that have the same length as the initial number of particles selected at iteration 2000, and the same tracked particle would have the same position within the array x1 and x2 for instance. Also, there would be NaNs in x1 if some of the particles were present at iteration 2000 but not anymore at the iteration 30000.

@ax3l @soerenjalas @MKirchen @jgerity : Does the above api make sense to you? Do you have suggestions for improvements, before I start coding?

**Comment by jgerity** [comment]
I'm not sure exactly how you'd be doing the `select` filtering on the back-end of that object, but if it does not prove to be too expensive, a suggested improvement would be to allow passing a callable for that argument so that the user can implement whatever selection criterion they'd like (vs choosing from a fixed set of criteria) as if they were using the `filter()` built-in. E.g.,

```python
pt = ParticleTracker(ts, species='electrons', select=momentumSelector, iteration=2000)

def momentumSelector(particle):
    return particle['uz'] > 10 and particle['uz'] < 100
```

**Comment by RemiLehe** [comment]
Thanks for this great suggestion.

Actually for implementing the `select` I was thinking about using the implementation from `ts.get_particle` within `ParticleTracker`. 
Currently, `ts.get_particle` can take a dictionary as argument for `select`. But it would definitely be a great ideat to allow the user to pass a callable, so as to give more flexibility ! 
But since this change (which would in the end mainly affect `ts.get_particle`) is somewhat independent of implementing particle tracking, I'll implement it in a separate pull request.

**Comment by soerenjalas** [comment]
I like your API approach, especially the idea to have a tracker object containing all information of the selected particles. Do you think having NaNs in the arrays can be a problem? For example do all numpy methods like NaNs? Otherwise, I think this would make a convenient API for a really handy tool!

**Comment by RemiLehe** [comment]
Yeah, I know the NaNs are not ideal since methods like `sum`, `mean`, etc. will return a Nan. However, you can use `np.nansum` and `np.nanmean` to ignore NaNs in the array (and compute the sum and mean on the values that are not NaNs). But I agree it is inconvenient. 

However, I think it is important that the same particles are returned always at the same position within the array, for different iterations. This is what allows users to reconstruct particle trajectories over several iteration. For instance:
```python
pt = ParticleTracker( ts, species='electrons', select={'uz':[10,1000]}, iteration=2000)

N_iterations = len(ts.iterations)
N_particles = pt.N_selected
X_trajectories = np.empty( ( N_iterations, N_particles ) )
for i in range( N_iterations ):
   x,  = ts.get_particles( ['x'], particle_tracker=pt, iteration=ts.iterations[i] )
   X_trajectories[i, :] = x[:]

trajectory_electron0 = X_trajectories[ :, 0 ]
trajectory_electron1 = X_trajectories[ :, 1 ]
```
However, if I return the same particle always at the same position in the array, I also need to fill the array with something when particles have exited the simulation box at later iterations, and this is where the NaNs are needed.

Does the above make sense? I am definitely open to other solutions that do not use the NaNs. But I think they have to maintain the property that individual trajectories can still be tracked. If you have any suggestions don't hesitate.

**Comment by jgerity** [comment]
Perhaps you could allow returning an array of ids in the resulting tuple? This lets the user track by ID byt keeping track of order in the two separate arrays, and shouldn't cause any breaking change if I've understood the `get_particle` method right. E.g.:

```python
pid, x, y, z = ts.get_particle( ['id', 'x', 'y', 'z'], particle_tracker=pt, iteration=50000 )
```

**Comment by soerenjalas** [comment]
Sorry for bringing the issue up without having a better solution… I completely see @RemiLehe's point and I also forgot about the NaN resistant numpy methods. So I think for most practical purposes having NaNs should be fine and for edge cases one could still filter the NaN with something like:
```python
trajectory_electron = np.where(trajectory_electron==NaN, 0)
```
Nevertheless, I think being able to get the particle id, as @jgerity said, is also a useful option. But I guess this will be the case anyway when the pid is a quantity of the species.

**Comment by RemiLehe** [comment]
@soerenjalas Yes, the API will support fetching iterations that are before the selection iteration. 

Regarding coding : I'm actually almost done, I'll do a PR soon. The most useful would be actually if you can continue checking that the choice of API I made is okay with you, and also if you can review the upcoming PR. :)

**Comment by RemiLehe** [comment]
Regarding the NaNs: in the end, I think I will add an option `preserve_particle_index` in the `ParticleTracker` object:
- If `preserve_particle_index` is True, then the same particle will always have the same index in the output array, so that we can easily track it as explained above. However, this implies that there will be NaN in the output array. 
- If `preserve_particle_index` is False, then there will be no NaNs (the output array will just have fewer elements because of the absent particles). But then it is not guaranteed, that particles are always at the same position. But then, as @jgerity pointed out, the user can still track particles "by hand", using their id. (In fact, outputting the id is already supported in openPMD-viewer).

So the user can choose `preserve_particle_index` depending on his/her purpose. `preserve_particle_index=True` is better for tracking, but `preserve_particle_index=False` is better for computing average quantities (emittance, etc.)

**Comment by RemiLehe** [comment]
Also, another change regarding the previous API I described: I think that passing the particle tracker under `select` would be actually nicer for the user, like so:
```
# Select particles at iteration 2000
pt = ParticleTracker( ts, species='electrons', select={'uz':[10,100]}, iteration=2000 )

# Fetch them at iteration 30000 and 50000
x1, y1, z1 = ts.get_particle( ['x', 'y', 'z'], select=pt, iteration=30000 )
```
This means that, in `get_particle`, `select` can either be a dictionary (with selection rules) or a `ParticleTracker` object (and soon a callable)>. This will allow methods like `get_emittance`, etc. to work directly with the particle tracker, without any change in the code.

**Comment by RemiLehe** [comment]
@jgerity @soerenjalas Let me know if you have any opposition, or further suggestion, to the above API (the `preserve_particle_index` and passing the `ParticleTracker` as `select`). If not, I will try to do a corresponding PR by the end of today.

**Comment by jgerity** [comment]
`preserve_particle_index` looks like a good compromise to me! I would think `False` would be a good default value, but you know better than I do what the typical user will want for this option. No other suggestions or objections.

**Comment by ax3l** [comment]
I like the API, it's clean and intiutive.

Regarding your `NaN` question, you could also go (optional?) for `numpy.ma` *masked arrays*.
