### ISSUE TITLE
utilities `list_h5_files` relies on time step in file name

### ISSUE THREAD

**Issue by PrometheusPi** [openPMD/openPMD-viewer#144]
Currently, all time series extractions are done using the `list_h5_files` function from `opmd_viewer.openpmd_timeseries.main`. This function extracts the time step from the last number before the suffix not from the time step in the hdf5 files. See code [here](https://github.com/openPMD/openPMD-viewer/blob/b7e84c060e7e049f532b324d8365a2b7c650b6cf/opmd_viewer/openpmd_timeseries/utilities.py#L47). Thus files like `libSplash` serial output will result in wrong time steps (the serial output extracts files with a given mpi rank as `filename_[timestep]_[rankx]_[ranky]_[rankz].h5`).

**Comment by RemiLehe** [comment]
Thanks for pointing out this issue!
Would you have the time to do a pull request to correct this? Otherwise I can also do it.

**Comment by PrometheusPi** [comment]
No problem. I will provide a pull request.
