### ISSUE TITLE
PIConGPU 2D x and y axis ranges are wrong 

### ISSUE THREAD

**Issue by PrometheusPi** [openPMD/openPMD-viewer#146]
When using `openPMD_viewer` - `OpenPMDTimeSeries` with the `slider()` method in 2D, the **ranges** of x and y axis are ~~**interchanged**~~ **wrong**.

Full call:
![openpmd_viewer_error01](https://cloud.githubusercontent.com/assets/5121158/23263630/1b40f47a-f9df-11e6-85c1-4d644005c8bf.png)

Zoomed into the plot output:
![openpmd_viewer_error02](https://cloud.githubusercontent.com/assets/5121158/23263750/76f5d3a8-f9df-11e6-88e7-ff98edd5db95.png)

In PIConGPU, the laser propagates in +y direction, as *correctly* marked by the axis labels. However, the ranges given are interchanged.  
(In this LWFA simulation, I used a moving window)

**Comment by PrometheusPi** [comment]
@HighIander this might effect your data analysis.

**Comment by ax3l** [comment]
is it really the range that is interchanged or only the offset of the start of the axis?

**Comment by ax3l** [comment]
probably similar to  #102 fixing #99

**Comment by PrometheusPi** [comment]
Actually, I just saw that the ranges (at iteration zero) make no sense at all. 
L_y = 0.4430e-7 m/cell * 2368 cells * (7 GPUs/8 GPUs) = 91.8 µm
L_x = 0.1772e-6 m/cell * 704 cells = 124.7 µm

vs. 

![b_at_0](https://cloud.githubusercontent.com/assets/5121158/23283228/2e8ceb1a-fa25-11e6-8ffb-02de27918cb9.png)

**Comment by ax3l** [comment]
weird. btw @HighIander and me won't see that. ion sims have
- no moving window
- quadratic cells

:-)

**Comment by PrometheusPi** [comment]
@ax3l but your simulation box size will not always be quadratic  thus it will effect you. 🤓

**Comment by ax3l** [comment]
no, that's `shape` and has nothing to do with the scaling of individual cells or their offset (in cells)

**Comment by ax3l** [comment]
I think I have the bug, as decribed in my post above.

`FieldMetaInformation` is working in Fortran order - we should switch that inside there.
Additionally, to not break Warp, we have to revert the read `gridSpacing`, `gridGlobalOffset` and `gridUnitSI` attributes if 'F' order is used inside `field_metainfo`

**Comment by RemiLehe** [comment]
I am not quite sure it is a Fortran order problem. Warp (like PIConGPU and FBPIC) has `dataOrder = C` in the openPMD metadata, because the output is done from the Python layer. 
Anyway, I am looking into the problem right now.

**Comment by ax3l** [comment]
Ok, I think the problem is, that we currently only switch `axisLabels` but we also need to switch `gridSpacing` & `gridGlobalOffset` the same way.

**Comment by RemiLehe** [comment]
Actually, looking at the PIConGPU HDF5 file, I see the following:
<img width="319" alt="screen shot 2017-02-23 at 3 57 52 pm" src="https://cloud.githubusercontent.com/assets/6685781/23284551/f6f32e06-f9e0-11e6-9af8-6e3a72f7249d.png">
So, if `axisLabels` and `gridSpacing` should indeed be in the same order (and thus match element-wise), this implies that the grid spacing in y is larger than in x, which contradicts @PrometheusPi above comment. 

I am misunderstanding the openPMD standard here, or is there something wrond with the PIConGPU output?

**Comment by ax3l** [comment]
I just cross-checked the file a minute ago in PIConGPU and I think I did invert the both `gridSpacing` and `gridGlobalOffset`. So the viewer is right and I have to fix the writer!
  https://github.com/ComputationalRadiationPhysics/picongpu/blob/ad355a4e5616733df4d47f8012e49b41eee6f7fd/src/picongpu/include/plugins/hdf5/writer/Field.hpp#L208-L227

But let me check this tomorrow again when its not 1:02 am :)

**Comment by RemiLehe** [comment]
Oh, ok, we reached the same conclusion simultaneously.

**Comment by ax3l** [comment]
Aww, sorry for that!
I even checked and fixed it for `axisLabels` when we cross-checked this last time but forgot the two others are affected, too.

**Comment by PrometheusPi** [comment]
great job - so it is no openPMD issue - I will thus close it

**Comment by ax3l** [comment]
right, I already opened and linked an issue in PIConGPU

**Comment by RemiLehe** [comment]
No, problem! Thanks for using the viewer anyway, and for contributing to its improvement!
