### ISSUE TITLE
field slider inverted 

### ISSUE THREAD

**Issue by PrometheusPi** [openPMD/openPMD-viewer#155]
The **slicing slider** in the *field view* of the `slider()` method is inverted.
It goes from `-1` to `+1` with `0` representing the center. At least for slicing in x in 3D `+1` is equal to the smallest x-cell-index while `-1` is equal to the highest x-cell-index. This is a bit counter-intuitive.

**Comment by RemiLehe** [comment]
Yes, this is definitely not the intended behavior. I'll have a look.

**Comment by ax3l** [comment]
just double checked it, seems to be a problem on our side. some delay debugging NaN values but we could not reproduce the "inversion" issue

**Comment by PrometheusPi** [comment]
I am sorry - the slider is correct. Perhaps my plot was just delayed thus I mixed the slider position and the according plot.

**Comment by RemiLehe** [comment]
Ok, thanks for letting me know :)

**Comment by ax3l** [comment]
Thanks for responding so quickly, I was two minutes too slow to spare you the hazzle :)
