### ISSUE TITLE
Need normalization for zero-mass particles

### ISSUE THREAD

**Issue by n01r** [openPMD/openPMD-viewer#156]
With the introduction of bremsstrahlung and Compton scattering into PIConGPU a photon model has been added to the available particle species. Since a photon's mass is zero we encounter a divide by zero during the normalization of the momentum data to (mc)^-1. 
```
/lib/python3.4/site-packages/opmd_viewer/openpmd_timeseries/data_reader/particle_reader.py:84: 
RuntimeWarning: divide by zero encountered in true_divide
  norm_factor = 1. / (get_data(species_grp['mass']) * constants.c)
```
In this case it would be desirable to have an arbitrary normalization and maybe a logarithmic plot scaling as a default. Then the users could set a normalization value by themselves after seeing the logarithmic plot and deciding where the regions of interest are and maybe change back to linear scaling. :grinning:

**Comment by RemiLehe** [comment]
OK, I agree with having arbitrary normalization in the case m=0. I'll do a pull request this evening (Pacific Time).

For the rest, I am not sure if the logarithmic plot is needed. Usually the plot range automatically adapts to the order of magnitude of the values that are being plotted, right?
