### ISSUE TITLE
python-dev missing causes error

### ISSUE THREAD

**Issue by PrometheusPi** [openPMD/openPMD-viewer#162]
This is more a question than an issue:
We tried to install openPMD-viewer via pip locally and encountered the problem that `Python.h` could not be found.
**Installing `python-dev` via pip solved this problem.**

Might this be a missing dependency for the pip install?

**Comment by RemiLehe** [comment]
Hmm, I never encountered that kind of issue before. On which platform did this happen? Are you able to reproduce it within a Docker environment, so that I can have a look at it?

**Comment by PrometheusPi** [comment]
Our college uses a "3.11.0-12-generic #19-Ubuntu SMP" on a  x86_64 (his own laptop).

Since neither he nor me have experience with Docker, probably not. 

He uses python 3.4. `python3-dev`was not installed and thus caused openPMD-viewer not to install via pip - failing with the above error. Installing `python3-dev` via pip solved it.

We followed the following instructions: http://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory.
I never encountered such a problem either and I have no system where to test it.

**Comment by PrometheusPi** [comment]
@steindev Could you test this on your local machine, perhaps it shows the same issue.

**Comment by steindev** [comment]
`python-dev` is installed on my local machine. Installation runs smoothly.

**Comment by steindev** [comment]
I just recognized on a freshly installed Ubuntu 16.04 that `python-dev` is a dependency of `pip` when it is installed via the package manager `apt-get`. So `python-dev` may not be a missing dependency of openpmd-viewer. Rather this points to an erroneously configured system. I suggest closing this issue.

**Comment by PrometheusPi** [comment]
@steindev Thanks for figuring out this dependency. 
I just spoke with our college, h can not reconstruct how he installed pip on his machine thus I will close this issue. 
@RemiLehe Sorry for bothering you again.

**Comment by RemiLehe** [comment]
OK, no worries. Thanks for taking the time to figure this out.
