### ISSUE TITLE
`%matplotlib` on MacOS will not let the plots pop-up

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-viewer#177]
It seems that there is a bug on the latest versions of `jupyter` for MacOS (which I did also experience in practice):
https://github.com/jupyter/notebook/issues/2960

This affects the default notebook that the users get when doing `openPMD_notebook`. I am tempted to switched the default notebook to `%matplotlib tk`. 
@ax3l @soerenjalas Any opinion on this? If there is no strong opinion against that, I'll make a corresponding PR, at least as a temporary measure until the bug is fixed.

**Comment by soerenjalas** [comment]
As a short term solution until the jupyter bug is fixed I see no problem with going to tk as the backend. 
Thanks for spotting this, I never use jupyter on a lokal machine so I wouldn’t have seen this behavior.

**Comment by ax3l** [comment]
Well spotted!

Hm, I am not sure it is a good idea to overwrite the mpl backends in lib code, tbh.

There are several locations where one can and should configure mpl including its default backend: in system configs, in user configs in the home and last but not least in user code:
- [matplotlibrc](https://matplotlib.org/tutorials/introductory/customizing.html#customizing-with-matplotlibrc-files)
- [mpl directories for configs](https://matplotlib.org/faq/troubleshooting_faq.html#locating-matplotlib-config-dir)

All of those default locations would be broken if we as a lib set the backend (which introduces additional docs and maintenance.) I would rather add a detection "if OSX + if recent version" and issue a warning.

If a packager for MacOS/OSX configures an ill backend, the best place is to complain to the packager (and to issue a note to OSX users to change that default in their user rc files).

**Comment by RemiLehe** [comment]
Actually, after thinking about it, I think I now have a stronger opinion towards changing the current default notebook from `%matplotlib` to `%matplotlib inline`.

In answer to @ax3l's comment: Note that this is not really lib code. What I am suggesting to modify is the default notebook that pops-up when doing `openPMD_notebook` (https://github.com/openPMD/openPMD-viewer/blob/master/opmd_viewer/notebook_starter/Template_notebook.ipynb). As such, the `%matplotlib inline` will not be burried in lib code, but instead it will be directly visible to the user (in the first cell of the notebook). Note also that this change will not affect the notebooks that users have previously created and modified.

The problem with the current `%matplotlib` setting is that:
- it will not work with MacOSX and the latest version of jupyter
- it will not work when the notebook is run on a remote machine.

In both of these cases, new users might think that `openPMD-viewer` just does not work, because no window pops up.

**Comment by RemiLehe** [comment]
Of course, we can also, as an additional measure, have code that checks if the backend is MacOSX so as to warn the user, as @ax3l suggested.

@ax3l: What do you think about the above?

**Comment by ax3l** [comment]
> What I am suggesting to modify is the default notebook that pops-up when doing openPMD_notebook

Ah, that's of course fine! Did not get you talk about the extra starter :)

> Of course, we can also, as an additional measure, have code that checks if the backend is MacOSX so as to warn the user, as @ax3l suggested.

Agreed, as an addition. Good idea!
