### ISSUE TITLE
LpaDiagnostic still depends on matplotlib

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-viewer#178]
While PR #172 removed the dependency on `matplotlib`, the `LpaDiagnostic` still depends on `matplotlib`. This should be corrected by using the same technique as in PR #172

**Comment by soerenjalas** [comment]
Hmm, my PR should have closed this one I though, maybe because it was merged into dev…

**Comment by RemiLehe** [comment]
OK, I'll close it anyway.
