### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-viewer#22]
We should probably add some Continuous Integration (CI) via http://travis-ci.org/ to automatically run a large sample of tests for the API for each PR before we merge it.

Idea: [pytest](http://pytest.org) and/or [tox](https://tox.readthedocs.org/en/latest/) (shamelessly stolen from [Open Sourcing a Python Project the Right Way](http://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/))

**Comment by RemiLehe** [comment]
Yes! This is something I have been considering for some time and have never had time to look into in mush details. But I think this is definitely the way to go.
