### ISSUE TITLE
openPMD_notebook problem

### ISSUE THREAD

**Issue by QJohn2017** [openPMD/openPMD-viewer#234]
HI, 
When I open the openPMD-viwer by typing `openPMD_notebook` in windows Powershell, there is only a script file occurred in Chrome:
![11](https://user-images.githubusercontent.com/31507149/58316866-26c91180-7e47-11e9-8ddb-7d6e225f69ca.jpg)

How to resolve it ?

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!

The command `openPMD_notebook` was never tested on a Windows system, so it is possible that it does not work in this case...

One alternative is to type `jupyter notebook` in a shell, then create a notebook (through the browser), and then fill the notebook with [this](https://github.com/openPMD/openPMD-viewer/blob/master/opmd_viewer/notebook_starter/Template_notebook.ipynb)

Does this work for you?

**Comment by QJohn2017** [comment]
Okay, when I type `jupyter notebook`, it works, thank you !

**Comment by QJohn2017** [comment]
I have another question, when I save the `*.ipynb` file as `.py` format and run it with python, some errors occurred:

`Traceback (most recent call last):
  File "1_Introduction-to-the-API.py", line 5, in <module>
    get_ipython().run_line_magic('matplotlib', 'inline')
AttributeError: 'NoneType' object has no attribute 'run_line_magic'` 

the python file is below:
![11](https://user-images.githubusercontent.com/31507149/58327538-710bbc00-7e62-11e9-9412-d9b654bf8056.jpg)

**Comment by RemiLehe** [comment]
I think that you need to either:
- run the above script with `ipython`: `ipython script.py`
- or remove the lines `from IPython import get_ipython` and `get_ipython().run_line_magic('matplotlib', 'inline')`
(These lines are not important if you are running a non-interactive script)

**Comment by QJohn2017** [comment]
but if I run the script without `from IPython import get_ipython` and `get_ipython().run_line_magic('matplotlib',` 'inline')` lines, there are no results and no figures were appeared

**Comment by RemiLehe** [comment]
@QJohn2017 You can use the `matplotlib` command `plt.savefig` to save the figure to a file in this case.

Again, the other solution is to use `ipython` instead of `python`: that should allow you to keep the lines with `get_ipython`.

**Comment by QJohn2017** [comment]
Okay, Thank you very much ! the problem has been solved!
