### ISSUE TITLE
Using get_current() for a plasma density profile which starts from vacuum

### ISSUE THREAD

**Issue by abonatto** [openPMD/openPMD-viewer#248]
Dear Developers,

In order to plot the current of plasma electrons along the beam propagation in a plasma, I am using LpaDiagnostics's get_current(). However, for a species which has not yet "been started" (for example, when the beam starts in vacuum and, after a given distance, there is a plasma density up-ramp), I get the following error:
```
ValueError: zero-size array to reduction operation maximum which has no identity
```
 Would you have any suggestion regarding how to deal with this no-plasma region in this situation? I thought of using try, except. However, I believe it would be interesting to have a better way to deal with it.

Cheers,

Alex

**Comment by ax3l** [comment]
Hi Alex,

thank you for the detailed report!
Soeren provided a fix via #250 which is now in `dev` - does that fix it for you?

**Comment by abonatto** [comment]
Hi Axel,

Sorry for taking so long to answer! I uninstalled/reinstalled via pip, using the following command to install the dev branch (please let me know if this is correct):
```
pip install git+https://github.com/openPMD/openPMD-viewer@dev
```
However, I had the same failure.

Cheers,

Alex

**Comment by ax3l** [comment]
Thanks!
Did you make sure it's definitely the new version you are using? e.g. `pip`/`pip3` mismatches, etc. You can verify usually with
```py
import <modulename> as foo
print(foo.__version__)
print(foo.__path__)
```
and check the sources under the path are what you expected.

**Comment by abonatto** [comment]
Yep. To double check, I pip-uninstalled it again, and tried to load it in python to ensure that there were no other versions installed. Then, i reinstalled it manually, using
```
git clone https://github.com/openPMD/openPMD-viewer
git fetch
git checkout dev
python setup.py install
```
After that, I confirmed the path and version using the commands you suggested me. However, I am still experiencing the following error (even when I load a .h5 file in which the plasma density is already initialised/non-zero):
```
In [51]: ts2.avail_species
Out[51]: [u'beam', u'electrons']

In [52]: beam_current = ts2.get_current(iteration=iter, species='beam')

In [53]: eplasma_current = ts2.get_current(iteration=iter, species='electrons')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-53-d19fabc1a152> in <module>()
----> 1 eplasma_current = ts2.get_current(iteration=iter, species='electrons')

/usr/local/lib/python2.7/site-packages/openPMD_viewer-0.9.0-py2.7-macosx-10.13-x86_64.egg/opmd_viewer/addons/pic/lpa_diagnostics.pyc in get_current(self, t, iteration, species, select, bins, plot, **kw)
    413             species=species, select=select )
    414         # Length to be seperated in bins
--> 415         len_z = np.max(z) - np.min(z)
    416         if w.size > 0:
    417             # Calculate Lorentz factor for all particles

/usr/local/lib/python2.7/site-packages/numpy/core/fromnumeric.pyc in amax(a, axis, out, keepdims, initial)
   2503     """
   2504     return _wrapreduction(a, np.maximum, 'max', axis, None, out, keepdims=keepdims,
-> 2505                           initial=initial)
   2506 
   2507 

/usr/local/lib/python2.7/site-packages/numpy/core/fromnumeric.pyc in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     84                 return reduction(axis=axis, out=out, **passkwargs)
     85 
---> 86     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     87 
     88 

ValueError: zero-size array to reduction operation maximum which has no identity
```
In my FBPIC script, I am defining the diagnostics as follows:
```
    sim.diags = [FieldDiagnostic(diag_period, sim.fld, comm=sim.comm),
                 ParticleDiagnostic(diag_period, {"electrons": elec},
                 select={"uz": [1., None]}, comm=sim.comm),
                 ParticleDiagnostic(diag_period, {"beam": beam},
                 particle_data=["position", "momentum", "weighting",
                                "E", "B", "gamma"], comm=sim.comm),
                 ParticleChargeDensityDiagnostic(diag_period, sim=sim,
                                                 species={"beam": beam}),
                 ParticleChargeDensityDiagnostic(diag_period, sim=sim,
                                                 species={"electrons": elec})]
``` 
Since the error only happens when using get_current for the plasma ("electrons" species), this makes me believe that I am defining things properly. However, if you see anything done wrong, please let me know. Meanwhile, I am evaluating the plasma through its density field rho (therefore, this issue is not critical for me now).

**Comment by soerenjalas** [comment]
Hi Alex,
I was able to reproduce your behavior. Sorry, I should have tested the fix more carefully… The issue was that there were still functions called on the empty particle arrays. Once PR #255 is merged I hope everything should work as planed.

**Comment by abonatto** [comment]
Hi Sören,

No worries! Thank you very much for your support :-)

**Comment by abonatto** [comment]
@soerenjalas, 

I was able to use it without that errors now (thank you). However, I have some additional observations:

1) After using get_current for both species,
```
    beam_current = ts.get_current(iteration=iter, species='beam')
    eplasma_current = ts.get_current(iteration=iter, species='electrons')
```
 eplasma_current[0] is now an array of zeros (as expected). However, it seems that all values of the spatial coordinate z of eplasma_current  are also set to zero:
```
In [14]: eplasma_current[1].z*1.e6
Out[14]: 
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           ...
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]: beam_current[1].z
Out[15]: 
array([1214.35506094, 1220.39341584, 1226.43177075, 1232.47012565,
            ...
           1794.03713172, 1800.07548663, 1806.11384153, 1812.15219643])

```
I suppose z coordinates are defined "dynamically", according to the positions of plasma electrons (when they are available)? Would it be possible to have z from the moving window, instead of an array of zeros?

2) The following plot shows rho_electrons for a given iteration,
![rho_electrons](https://user-images.githubusercontent.com/10319592/70923133-4a3fed80-201f-11ea-8f9c-8dc0cad88233.png)
and this is rho_electrons on-axis:
<img width="665" alt="Captura de Tela 2019-12-16 às 16 16 25" src="https://user-images.githubusercontent.com/10319592/70923203-69d71600-201f-11ea-8ac0-9a0678c8ed55.png">

When I use get_current for these electrons, I am also getting an array of zeros,
![current_electrons](https://user-images.githubusercontent.com/10319592/70923449-d05c3400-201f-11ea-94b6-044ece990776.png)

Is this correct / expected?

**Comment by soerenjalas** [comment]
Yes, for now this is the expected behavior. Currently, the method `get_current()` only calls `get_particle()` and therefore has no information about the actual simulation grid. In principle, there could be particle data without an a grid present if you assume data that is not generated by a PIC code. 
But I agree with you that this behavior is not ideal. Maybe we could implement something like the `use_field_mesh` flag in `get_particle`.

**Comment by abonatto** [comment]
Ok, right. Thank you for the explanation! Your suggestion about a future implementation of the `use_field_mesh` flag sounds really interesting :-)

**Comment by abonatto** [comment]
Just for sake of closure, in my previous comment (2nd observation) the plot for the current of plasma electrons was empty because I was selecting only particles with uz > 1. By removing this selection (and running again my simulation), I am able to see the plasma e-current as expected:
<img width="635" alt="Captura de Tela 2019-12-16 às 17 22 41" src="https://user-images.githubusercontent.com/10319592/70928675-6ea0c780-2029-11ea-943c-8bbaa5379566.png">
