### ISSUE TITLE
Drop python 3.4 support

### ISSUE THREAD

**Issue by soerenjalas** [openPMD/openPMD-viewer#251]
As far as I understand Python 3.4 has reached its end of lifetime and support has already been dropped in many places (pip, pytest, conda). For example, our test are failing because miniconda cannot download python 3.4 anymore. Should we also drop support for 3.4?

**Comment by ax3l** [comment]
Sounds good - shall we add Python 3.8 Support at the same time?

**Comment by ax3l** [comment]
Actually, #241 did this already for the upcoming branch. Will backport.

**Comment by ax3l** [comment]
3.4 dropped and 3.7 and 3.8 added in `dev` and `upcoming-1.0` :)
