### ISSUE TITLE
About slicing

### ISSUE THREAD

**Issue by cbontoiu** [openPMD/openPMD-viewer#261]
I have some hdf5 data with particles and fields from the picongpu code. I try to make sense of my results using the slicing attribute as:
```Matlab
Ey, info_Ey = ts.get_field(iteration=2*step, field='E', coord='y', slicing_dir='y', slicing=0.1, 
                           plot=True, cmap = 'bwr')
```
thinking that since I have a cube simulation domain I slice it perpendicular to the y-axis with slicing=0 being the mid-plane xz for that cube. In this case taking slicing=0.1 as above, should give the snapshot of Ey at 10% of the domain y-length further away towards the positive y-axis. Thus I could get data up to slicing=0.5 and down to slicing=-0.5. Is this right? Thank you.

**Comment by ax3l** [comment]
Hi Cristian,

In PIConGPU, the default laser propagation direction is `y`. It's therefore probably easiest to check a slice in `x-y` first, by taking `slicing_dir='z'` in a 2D3V simulation. In 3D3V, you can also slice in `slicing_dir='x'` for "z-y". Slicing in `slicing_dir='y'` is a slice orthogonal to the laser propagation and depending on the choice of relative `slicing=` position can indeed be a bit confusing to look at.

By default, the laser pulses are linearly (or in some examples circularly) polarized in PIConGPU (check your input's `laser.param` to make sure). The default linear polarization is `x`.

Yes, `slicing=0.0` is the middle of the simulation.
You can find the full argument description for the `.get_field` method when executing in IPython or Jupyter notebook on a new line:
```
ts.get_field?
```

Based on the example above, try this:
```py
Ey, info_Ey = ts.get_field(iteration=2*step,
    field='E', coord='x',
    slicing_dir='z', slicing=0.0,
    plot=True, cmap = 'bwr')
```

**Comment by RemiLehe** [comment]
@ax3l Thanks for the clarification.
@cbontoiu Your understand of slicing is correct, except that `slicing` can go from `-1` to `1`, not `-0.5` to `0.5` (see the docstring of `get_field`: https://github.com/openPMD/openPMD-viewer/blob/master/opmd_viewer/openpmd_timeseries/main.py#L399)

I admit that the convention `-1` to `1.` is arguably confusing. With this convension, `slicing=0.1` would be located at 5% of the box length, starting from the middle of the box (or 55% of the box length, starting from the lower boundary)

**Comment by cbontoiu** [comment]
Thanks for the replies. I also wonder how can I extract field and particle information along a line, for example along the line x = 0, y = 0 that is all the way along the z dimension of the simulation box through its centre. Is there a manual for these things?

**Comment by RemiLehe** [comment]
@cbontoiu 
Regarding slicing of the fields along a 1D line: This will be available in the next major release of `openPMD-viewer` (release 1.0), and is in fact already available on the branch `upcoming-1.0` of this Github repository. When using this branch, you can do:
```
get_field( ..., slicing_dir=['x', 'y'] )
```
in order to get a 1D slice along `'z'`.

Regarding the particles: you can use the `select` argument of `get_particle` and get the particles inside a thin "pencil" in x and y:
```
get_particle( ... , select={'x':[-0.5e-6, 0.5e-6], 'y':[-0.5e-6, 0.5e-6]} )
```

**Comment by cbontoiu** [comment]
Thanks. How can I install the development version then? The current version was installed with 

```pip install openPMD-viewer```

so I thought 

```pip install openPMD-viewer@upcoming-1.0```

would work but it didn't.

Anyway, I would also need to extract the data in text format so that I can make plots using entries from multiple simulations. How can these be extracted from hdf5?

**Comment by RemiLehe** [comment]
@cbontoiu You can use:
```
pip install git+https://github.com/openPMD/openPMD-viewer.git@upcoming-1.0
```

Regarding your second question: you can extract the data as numpy arrays using `get_field`/`get_particle` and then write them to a text file using `numpy.savetxt`.

**Comment by ax3l** [comment]
(set the argument `plot=False` if you only want data from these functions)
