### ISSUE TITLE
openPMD Viewer with ADIOS

### ISSUE THREAD

**Issue by cbontoiu** [openPMD/openPMD-viewer#268]
I try to use the ```OpenPMD_Viewer``` in ```Jupyter``` for loading files created (and possibly compressed) by PIConGPU with the ```ADIOS``` plugin. However I get an error as shown in the image below

![73839283-8157a180-480d-11ea-96a5-5a8e1f94cb6e](https://user-images.githubusercontent.com/7108691/73841621-e366d580-4812-11ea-9c71-f2038dc5e5ae.png)

I understood that adios is not installed for me in a system-wide location (only in Spack so only PIConGPU can use) and I tried to follow the instructions found here

https://github.com/ornladios/ADIOS/tree/master/wrappers/numpy

Everything went fine until the command ```pip install adios``` when I get the following error

![Screenshot_2020-02-05_12-30-30](https://user-images.githubusercontent.com/7108691/73841855-57a17900-4813-11ea-9ba7-8002f11d6128.png)

Could anyone help me with this? Alternatively I might be able to install ```ADIOS``` direclty not through ```pip``` but I am afraid that won't be picked up by ```openPMD viewer``` which itself was installed using ```pip```.

Thank you
Cristian

**Comment by ax3l** [comment]
Hi Cristian,

openPMD-viewer is not yet build on top of openPMD-api. It therefore uses `h5py` so far to read data, which limits current file format support to HDF5.
You have the following options until then:
- if you want to read the data to numpy, use openPMD-api directly
- if you want to use openPMD-viewer for its GUI, convert the data via `bp2h5` in ADIOS1 or write the data to HDF5 in PIConGPU's HDF5 plugin.

Does that help so far?

**Comment by cbontoiu** [comment]
Hi Axel,

Thanks, it helps! All I wanted was to reduce the data size and I noticed that using ADIOS this can be done. Now your script to compress the .h5 files helps me already with that. The only addition to the script would be to make it work automatically as soon as a new .h5 file is generated. I will try to work it out myself.

Kind Regards

**Comment by ax3l** [comment]
Just as an update: #285 implemented `openPMD-api` and thus ADIOS1/ADIOS2/HDF5/JSON support as a backend for `openPMD-viewer`.

You can test it already by installing the latest `dev` version of `openPMD-viewer` until the next release is out.
We also just started shipping `pip` binary wheels of `openPMD-api` for Windows as an alternative to Conda (which already shipped them).

**Comment by ax3l** [comment]
Released with the `1.1.0` release :)
