### ISSUE TITLE
addon:pic:get_emittance micron to meters conversion

### ISSUE THREAD

**Issue by hightower8083** [openPMD/openPMD-viewer#275]
were multiplications like these
https://github.com/openPMD/openPMD-viewer/blob/2d0d7d86077e3610a6d647380ad3c8ec46b6526b/openpmd_viewer/addons/pic/lpa_diagnostics.py#L323-L324
and this 
https://github.com/openPMD/openPMD-viewer/blob/2d0d7d86077e3610a6d647380ad3c8ec46b6526b/openpmd_viewer/addons/pic/lpa_diagnostics.py#L428
supposed to stay here after the update to 1.0?

**Comment by soerenjalas** [comment]
Good catch! Thanks a lot. I'll prepare a fix.

**Comment by hightower8083** [comment]
and this thanx goes to our post-doc Julius Huijts who've got stumbled by it doing emittance study =)
