### ISSUE TITLE
speed up data collection

### ISSUE THREAD

**Issue by cbontoiu** [openPMD/openPMD-viewer#280]
Hello, I need to compare longitudinal and transverse electric fields retreived from .h5 files using the openPMD viewer. There may be up two three axes, each defined by an index of the cell along x such as ```xCellNo1 = round(cellsX/2); xCellNo2 = round(cellsX/4); xCellNo3 = round(cellsX/8);``` where cellsX is the number of cells used along X.

I have two questions, for which I wou kindly ask some guidance:
1) With ```aEx=ts.get_field(iteration=it,field='E',coord='x');```, suppose I want to collect the field along the y-axis at a given coordinate, say ```x = 10.5 nm``` not at a certain cell number on X. How can I replace the aproximate xCellNo1 in ```aEx[0][j, xCellNo]``` with the real distance such as  ```aEx[0][j, 10.5e-09]```?

2) For a 2D simulation, where the cut plane makes no sense, I normally use the code below to loop over all (wanted) cells along the y-axis and collect transverse field components at up to three X positions. It works fine but it runs terribily slow, especially with higher mesh quality. In order to speed uo, is there a way to obtain these fields at once instead of looping along y with the j index?

```
if it in ts.iterations:
    aEx=ts.get_field(iteration=it,field='E',coord='x');
    aEz=ts.get_field(iteration=it,field='E',coord='z');
    onAxisEX1 = []; onAxisEZ1 = []; 
    onAxisEX2 = []; onAxisEZ2 = []; 
    onAxisEX3 = []; onAxisEZ3 = [];
    j = YLIM_DOWN
    while j < YLIM_UP: 
        if axis1:
            onAxisEX1.append(aEx[0][j, xCellNo1]*1e-9); # in GV/m
            onAxisEZ1.append(aEz[0][j, xCellNo1]*1e-9); # in GV/m
        if axis2:
            onAxisEX2.append(aEx[0][j, xCellNo2]*1e-9); # in GV/m
            onAxisEZ2.append(aEz[0][j, xCellNo2]*1e-9); # in GV/m
        if axis3:
            onAxisEX3.append(aEx[0][j, xCellNo3]*1e-9); # in GV/m
            onAxisEZ3.append(aEz[0][j, xCellNo3]*1e-9); # in GV/m          
        j += 1;
```

Thank you,
Cristian

**Comment by ax3l** [comment]
Hi Christian,

this looks to me like it can be achieved without loops via the ND-array slicing syntax in Python and Numpy. Do the reference and this tutorial help you?

- https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
- https://www.geeksforgeeks.org/indexing-in-numpy/

**Comment by RemiLehe** [comment]
In addition to Axel's suggestion, you could also try the argument `slice_relative_position`.
For instance, if the `x` axis of the simulation box extends from, say, -7 microns to +36 microns (arbitrary numbers here), you would do:
```
slice_relative_position = -1 + 2*((10.5 + 7)/(36 + 7))
Ex, info = ts.get_field( 'E', 'x', slice_across='x', slice_relative_position=slice_relative_position)
```

I agree that the calculation of the "relative position" with respect to the position box is a bit cumbersome (esp. because `slice_relative_position` goes from -1 to 1, not 0 to 1 ; see the docstring of `ts.get_field` for more explanation).

We are planning to also add an optional argument `slice_absolute_position`, in order to make this easier ; however, this is not implemented yet.

**Comment by ax3l** [comment]
P.S.: you can get the doc string of `ts.get_field` with either `ts.get_field?` in a jupyter notebook or via `help(ts.get_field)`.

**Comment by ax3l** [comment]
I am closing this issue for now as answered, but feel free to chime back in in case there are further iterations needed.
