### ISSUE TITLE
Beam emittance in LWFA

### ISSUE THREAD

**Issue by StevE-Ong** [openPMD/openPMD-viewer#282]
Hi, I am measuring the beam emittance in LWFA from the simulation output in PIConGPU. I follow the step in the tutorial and measure the emittance `kind=normalized`, and projected. The value that I obtain is very small. I got (4.87e-11, 2.78e-9) in the unit of m rad. I am not sure but it seems extraordinarily small. I wonder if I make some mistake? Thanks.

[e_Den_PIConGPU_18000.pdf](https://github.com/openPMD/openPMD-viewer/files/4514295/e_Den_PIConGPU_18000.pdf)

**Comment by soerenjalas** [comment]
Hi Steve,
This seems indeed very small. Would you mind sharing the command you are calling to calculate the emittance? Have you plotted the phase space (e.g. x vs. ux) of the particles you use to see if there is something wrong with that?

Thanks

**Comment by StevE-Ong** [comment]
Thank you for your reply. I have the following command for calculating emittance in another example:

```
from openpmd_viewer.addons import LpaDiagnostics
filename="lwfa018_rstrt30001"
h5_dir = get_h5path(filename)
ts_2d = LpaDiagnostics(h5_dir)

select_pos={'x' : [22e-6,37e-6],'y' : [580e-6,600e-6],'z' : [22e-6,37e-6]}

emit = ts_2d.get_emittance(iteration=30001, species='e',select=select_pos
                    , kind='normalized', description='projected')
print('emittance x [pi mm mrad]=', emit[0]*1e6)
print('emittance y [pi mm mrad]=', emit[1]*1e6)
emittance x [pi mm mrad]= 5.176391630183826e-05
emittance y [pi mm mrad]= 0.0015586504961469887
```
For `kind='trace'`:

```
emittance x [pi mm mrad]= 0.010002424560146366
emittance y [pi mm mrad]= 0.9113301403623294
```

The ux vs x and uy vs y plotted from OpenPMDTimeSeries plots are as follow:

![Unknown-2](https://user-images.githubusercontent.com/52823653/79964486-7a970d00-8493-11ea-9c57-e57545789b82.png)

![Unknown](https://user-images.githubusercontent.com/52823653/79964551-8be01980-8493-11ea-9eae-d9d969d982e0.png)

**Comment by soerenjalas** [comment]
Okay,
I'm assuming y is to longitudinal coordinate in you simulation? Currently, openPMD-viewer assumes that x and y are the transverse components. This is something we need to fix. 
There was an issue about units that was recently fixed. Could you check that you have the newest version installed? You can check by running the following two lines in a notebook or python shell:

```
import openpmd_viewer
openpmd_viewer.__version__
```

**Comment by StevE-Ong** [comment]
The version I am using is 1.0.0

**Comment by soerenjalas** [comment]
In that case updating to 1.0.1 should probably fix the issue in x. As for y which is z in your case we would have to change the code.

**Comment by StevE-Ong** [comment]
I am using PIConGPU. The moving window moves in the y-direction. So y is the longitudinal coordinate. After updating to version-1.0.1, I obtain the following:

```
emit = ts_2d.get_emittance(iteration=30001, species='e',select=select_pos
                    , kind='normalized', description='projected')
print('emittance x [pi mm mrad]=', emit[0]*1e6)
print('emittance y [pi mm mrad]=', emit[1]*1e6)
emittance x [pi mm mrad]= 51.76391630183833
emittance y [pi mm mrad]= 1558.6504961469993
```

**Comment by soerenjalas** [comment]
The value for x seems reasonable considering the large transverse momentum in the plot above.

**Comment by StevE-Ong** [comment]
So which mean that emittance_x now is one of the component of transverse emittance, and emittance_y is the longitudinal emittance?

**Comment by StevE-Ong** [comment]
Hi, borrowing the code from openpmd_viewer, I did the following:
```
ts = OpenPMDTimeSeries(h5_dir, check_all_files=False)
def w_ave( a, weights ):
       xxxx   
def emittance_from_coord(x, y, ux, uy, w):
       xxxx

iteration=30001
select_pos={'x' : [22e-6,37e-6],'y' : [580e-6,600e-6],'z' : [22e-6,37e-6]}
x, z, ux, uz, w = ts.get_particle(
            var_list=['x', 'z', 'ux', 'uz', 'w'],
            iteration=iteration, species='e', select=select_pos )
emit = emittance_from_coord(x, z, ux, uz, w)
print('emittance x [pi mm mrad]=', emit[0]*1e6)
print('emittance z [pi mm mrad]=', emit[1]*1e6)

emittance x [pi mm mrad]= 51.76391630183833
emittance z [pi mm mrad]= 34.225688728966226
```
for `kind='normalized'`
So I guess this is the transverse beam emittance?

**Comment by soerenjalas** [comment]
Good fix! Yep that should work.

**Comment by StevE-Ong** [comment]
Thank you @soerenjalas
