### ISSUE TITLE
FBPIC running on cpu on greatlakes cluster despite use_cuda=True 

### ISSUE THREAD

**Issue by andrefantoine** [openPMD/openPMD-viewer#284]
Since the most recent update of FBPIC (v0.17), 

Issue number 1) I have had an issue where the greatlakes system (University of Michigan HPC cluster) does not run the process unless I load the proper modules before submitting the script (an issue I did not have beforehand).
**See link below**

Issue number 2) Even with use_cuda = True and the partition in the submission script set to GPU FBPIC persists to run on cpu. 

[example1.txt](https://github.com/openPMD/openPMD-viewer/files/4953993/example1.txt)

**Comment by soerenjalas** [comment]
Hi,
could you repost this issue on the [ FBPIC repository](https://github.com/fbpic/fbpic)
Thanks!

**Comment by andrefantoine** [comment]
Yes, sorry
