### ISSUE TITLE
compatibility issues of new openpmd-api

### ISSUE THREAD

**Issue by hightower8083** [openPMD/openPMD-viewer#296]
Hi @RemiLehe  and @ax3l 

I've tested the new `openpmd-api` integration (using `openpmd-api@0.12.0a` from *conda*), and I have some comments:
- for WarpX it works well for 2D (not tested 3D) for `bp` and `h5` backends
- for WarpX with RZ it shows `cartesian2d` geometry and does not get any modes, but I guess its  (see [#1543](https://github.com/ECP-WarpX/WarpX/issues/1543) )
- for FBPIC it does not work at all returning 
```[HDF5] Internal error: Failed to open HDF5 attribute during attribute read```
- with FBPIC, if I force the `h5py` backend (see #295 ), it can read but only the vector fields (`E`, `B` and `J`), while scalars (`rho` and `rho_`) fail returning `'Unable to open object (message type not found)'` at `dset = dfile[ full_field_path ]` in `find_dataset(dfile, field_path)` function

**Comment by ax3l** [comment]
Thank you for the testing and great report!

for the 3rd and 4th point: Rémi will create a file here from FBPIC that I can use to debug 3 and he will look into 4.

**Comment by RemiLehe** [comment]
Here is the corresponding file
[Uploading diags.zip…]()

**Comment by RemiLehe** [comment]
@ax3l Here is a smaller reproducer for 3rd point in the original message by @hightower8083 (i.e. `openpmd-api` being unable to read FBPIC files):
```
import openpmd_api as io
io.Series('./diags/hdf5/data%T.h5', io.Access.read_only )
```
(This uses the files that I posted as a zip file.)

In this case, I get the following error:
```
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: H5A.c line 425 in H5Aopen(): unable to load attribute info from object header for attribute: 'value'
    major: Attribute
    minor: Can't open object
  #001: H5Aint.c line 433 in H5A__open(): unable to load attribute info from object header for attribute: 'value'
    major: Attribute
    minor: Can't open object
  #002: H5Oattribute.c line 515 in H5O__attr_open_by_name(): can't locate attribute: 'value'
    major: Attribute
    minor: Object not found
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-3328cf1da57f> in <module>
----> 1 io.Series('./diags/hdf5/data%T.h5', io.Access.read_only )

RuntimeError: [HDF5] Internal error: Failed to open HDF5 attribute during attribute read
```
Any idea what might be going on here?

**Comment by RemiLehe** [comment]
@ax3l I ran the openPMD-viewer validator on the above-mentioned file, and it shows no error (only warnings):
```
Warning: Attribute author (recommended) does NOT exist in `/`!
Warning: Attribute softwareVersion (recommended) does NOT exist in `/`!
Found 1 iteration(s)
Iteration 50 : found 4 meshes
Iteration 50 : found 1 particle species
Warning: Key particlePatches (recommended) does NOT exist in `/data/50/particles/electrons`!
Result: 0 Errors and 3 Warnings.
```
Could it be that the `openpmd-api` tries to read one of these optional attributes?

**Comment by ax3l** [comment]
Thank you for the details!
I debugged the data set and improved the error message.
```
  what():  [HDF5] Internal error: Failed to open HDF5 attribute 'value' (/data/50/particles/electrons/momentum/x/) during attribute read
```

In short, the constant record components
```
/data/50/particles/electrons/positionOffset Group
/data/50/particles/electrons/positionOffset/x Group
/data/50/particles/electrons/positionOffset/y Group
/data/50/particles/electrons/positionOffset/z Group
```
need a `.value` attribute (of zero) :)

- [ ] fix in validator
- [ ] fix in FBPIC

**Comment by ax3l** [comment]
The problem is fixed upstream via https://github.com/openPMD/openPMD-api/pull/849 and will land via the next openPMD-api release (the current stable release is `0.12.0`).
