### ISSUE TITLE
openPMD-viewer visualize static field

### ISSUE THREAD

**Issue by lge0303** [openPMD/openPMD-viewer#312]
The attached zip file includes 4 static fields, no errors from openPMD-validator check, they could be visualized by yt. There are errors for loading through openPMD-viewer.
[hdf5.zip](https://github.com/openPMD/openPMD-viewer/files/6166283/hdf5.zip)

**Comment by ax3l** [comment]
Hi @lge0303,

I looked at your files and they look great. Here is a work-around for you to visualize them:
```py
ts = OpenPMDTimeSeries('./hdf5/', backend='h5py')
```

There is an ambiguity / small defect in the openPMD standard with respect to `particlesPath` that I need in openPMD-api to make this more robust. Will be fixed with the next openPMD-api release (the latest one is 0.13.2).

Refs.:
- https://github.com/openPMD/openPMD-standard/issues/253

**Comment by ax3l** [comment]
@lge0303 now that I debug this - actually, you just need to update your `openPMD` attribute from `1.0.0` to `1.1.0`.

The relaxation that `particlesPath` is optional was introduced in that version of the standard.

**Comment by lge0303** [comment]
Axel,

Thank you very much for solve this issue 😊

Lixin


From: Axel Huebl ***@***.***>
Reply-To: openPMD/openPMD-viewer ***@***.***>
Date: Wednesday, March 24, 2021 at 5:36 PM
To: openPMD/openPMD-viewer ***@***.***>
Cc: lixin ge ***@***.***>, Mention ***@***.***>
Subject: Re: [openPMD/openPMD-viewer] openPMD-viewer visualize static field (#312)


@lge0303<https://github.com/lge0303> now that I debug this - actually, you just need to update your openPMD attribute when you write from 1.0.0 to 1.1.0.

The relaxation that particlesPath is optional was introduced in that version of the standard.

**Comment by ax3l** [comment]
@lge0303 please feel free to report back once you have a chance to test this with the modified `openPMD` attribute and then we will close this issue :)

**Comment by lge0303** [comment]
Attached is the zip file for these files modified following your suggestions: attribute from 1.0.0 to 1.1.0.

Somehow I could not connect kernel on jupyter, so can not check the results now :-(. Do you have any suggestions for fixing the "kernel not found" on nersc jupyter?  Thanks!
[hdf5.zip](https://github.com/openPMD/openPMD-viewer/files/6223144/hdf5.zip)

**Comment by lge0303** [comment]
@ax3l forgot ping you

**Comment by lge0303** [comment]
@ax3l I successfully use OpenPMD-viewer visualizing the static field. you can close this issue.

Thanks!
