### ISSUE TITLE
Tutorial Links in README.md

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-viewer#324]
@georgekholt reported on twitter that our README.md has outdated tutorial links (we changed the branch names).

He agreed to submit a PR for a fix :)

**Comment by georgeholt1** [comment]
Hi @ax3l,
I noticed a previous commit (https://github.com/openPMD/openPMD-viewer/commit/853710d9d68d17185504fd9bf2b7d5b89fcc5a15) that changed the links from 'master' to 'main', but it seems the `main` branch no longer exists, which is causing the dead links. Is `dev` the release branch? If so, I'll fix the links to point there instead.

**Comment by marc-marcos** [comment]
@georgeholt1 I'd say the current branch is the `master` branch, as it is the one that's currently being used, at least that's what I did in #325. If that's not the case @ax3l let me know and I'll close it.

**Comment by ax3l** [comment]
Fixed by #325

Thank you both!! :)
