### ISSUE TITLE
`get_particle()` gives different results if parameter `select` is given a dictionary or a `ParticleTracker` with identical dictionary

### ISSUE THREAD

**Issue by felipepena1** [openPMD/openPMD-viewer#339]
Hello,
I'm trying to identify some particles at the beginning of the simulation and then look at them at a later stage of a simulation. For this I would like to use `ParticleTracker()`. I'm having some problems though and I'm not sure if it is due to some misunderstanding from my side or a bug.

From my understanding, the following two code blocks should give the same output:

    from openpmd_viewer.addons import LpaDiagnostics
    
    ts = LpaDiagnostics(path, check_all_files=False)
    ts.get_particle(['z', 'uz'], iteration=0, select={'z': [0, None]}, plot=True, vmax=1E6)

and

    from openpmd_viewer.addons import LpaDiagnostics
    from openpmd_viewer import ParticleTracker

    ts = LpaDiagnostics(path, check_all_files=False)
    pt = ParticleTracker(ts, iteration=0, select={'z':[0, None]})
    ts.get_particle(['z', 'uz'], iteration=0, select=pt, plot=True, vmax=1E6)

What is plotted with the first piece of code is:
![image](https://user-images.githubusercontent.com/103264857/162454742-e42c7339-9918-477c-97ea-c8cd4328df09.png)
 while the second piece of code plots:
![image](https://user-images.githubusercontent.com/103264857/162454796-5c1a41fa-3864-4864-99c7-5a55cd29b94c.png)

The total number of electrons returned by `ts.get_particle()` is the same in both cases.

I would be very thankful for any help, as I'm thankful for openPMD-viewer :)

**Comment by RemiLehe** [comment]
Thanks a lot for reporting this issue!
This is indeed unexpected. If it is not too large, would you be able to upload the data file for iteration 0 here? That way, I could investigate the problem in more detail.

**Comment by felipepena1** [comment]
Yes, no problem from my side. I could not upload it here, it gives me an 'is not included in the list' error (even as .zip file), but I uploaded it in this link: https://syncandshare.desy.de/index.php/s/9p27J4TPE7L5jNp
Thank you for looking into it

**Comment by RemiLehe** [comment]
OK, thanks for the update. 
`ParticleTracker` indeed works with particle IDs [see the code here](https://github.com/openPMD/openPMD-viewer/blob/dev/openpmd_viewer/openpmd_timeseries/particle_tracker.py). Feel free to post the later data files here (the ones with fewer duplicated IDs).

**Comment by RemiLehe** [comment]
Hm, I looked into this a bit more, and it seems that some of the particles with `z<0` have the same IDs as some of the particles with `z>0`. 

Thus, when trying to fetch the particles with `z>0` based on the ID only, `openPMD-viewer` sometimes fetches some of the particles with `z<0` that have the same ID.

It would be interesting to see whether you still see an issue once HiPACE only dumps unique IDs.

**Comment by felipepena1** [comment]
Okay, so the issue with the IDs has been solved and now there are unique IDs in the new files. And `ParticleTracker` seems to work as expected, great!

I'm sorry for any possible confusion I might have created. I'm new to the simulation world.

Does it make sense to have a check in `ParticleTracker` in case there are repeated IDs since this would cause problems? I checked it via `len(IDs) == len(set(IDs))`. Just a suggestion though, I'm not sure if this would be too much computation for something that generally should be the case.

**Comment by RemiLehe** [comment]
Thanks for the clarification, and happy to learn that the problem has been fixed :)

Yes, I was also thinking of adding a check like `len(IDs) == len(np.unique(IDs))`. From what I read, the time complexity of `np.unique` is `N log(N)`, so it's not too bad. (We are paying an `N log(N)` price anyway because we sort the IDs.) If you already know how to add this in the code, feel free to open a PR. Otherwise, I might also do it in a few days from now.
