### ISSUE TITLE
Tests are failing for python 3.6

### ISSUE THREAD

**Issue by soerenjalas** [openPMD/openPMD-viewer#360]
Currently the tests for python 3.6 are failing (e.g. in PR #359 ). In the test step of the actions pipeline pip tries to install a version of ipykernel, which doesn't support 3.6. I tried installing ipykernel directly when setting up the conda environment but this did not help for some reason.

I also noticed that conda has an increasingly hard time to solving the installation requirements for 3.6. Maybe its time to acknowledge the EOL of 3.6 and drop support (or at least not test for it).

**Comment by ax3l** [comment]
Thx for reporting!

Fixed via #364
