### ISSUE TITLE
Exception for erroneous `field` and  `var_list` arguments

### ISSUE THREAD

**Issue by soerenjalas** [openPMD/openPMD-viewer#38]
Hi,
I came across some minor annoyances when using the api in rather long python scripts. When using wrong `field` or `var_list` arguments in `get_field` or `get_particle` we currently issue a warning in form of a python print: 

```python
if valid_var_list == False:
            quantity_list = '\n - '.join( self.avail_ptcl_quantities )
            print("The argument `var_list` is missing or erroneous.\nIt "
                  "should be a list of strings representing particle "
                  "quantities.\n The available quantities are: "
                  "\n - %s" %quantity_list )
            print("Please set the argument `var_list` accordingly.")
            return(None)
```
This has the downside of not knowing where exactly in the code the error occurs. Something like

```python
field = get_field(t, field=bogus)
```
is then passed as `NoneType` and will lead to errors further down the road.
My suggestion would be to additionally throw an exception to have a proper python traceback. Would this lead to errors with the interactive interface?

**Comment by RemiLehe** [comment]
Yes, that makes sense. We could raise a custom Exception, for instance an `OpenPMDException`. 
Actually, since this it is quite fast, I implemented this in pull request :

Is that okay with you ? 
@ax3l : any thought on how you would like the API to behave when the user asks for quantities that do not exist in the file (e.g. requesting iteration 500 when only iteration 0 and 1000 are present). Is throwing a custom exception okay with you ?

**Comment by ax3l** [comment]
Yes, I think that is the right way to go to to raise exceptions when api calls are failing. It's still useful when interfaces exist that can be queried beforehand for available quantities (to avoid extensive try constructs in user code).

**Comment by soerenjalas** [comment]
Thanks for the quick response! That's exactly what I was thinking of.

**Comment by RemiLehe** [comment]
Great, thanks for the feedback :)
@soerenjalas : you can merge the pull request and close the issue, if that's fine with you.

**Comment by ax3l** [comment]
added cross references to the PR/issue.
