### ISSUE TITLE
FieldProbe only outputs E and B field

### ISSUE THREAD

**Issue by ashwynsam** [openPMD/openPMD-viewer#395]
Hello,

When using `ReducedDiags` and setting `<reduced_diags_name>.type = FieldProbe`it only outputs the E and B field at a particular point. However, I want other variables like the Ion Denisty at a particular point. Would it be possible to add other variables to the `FieldProbe` output? 

Thank you

**Comment by ax3l** [comment]
Hi @ashwynsam , please open this in https://github.com/ECP-WarpX/WarpX/issues
