### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by cbontoiu** [openPMD/openPMD-viewer#404]
Hi,

I have a new installation of PIConGPU dev with gcc 11.4.0
It seems that the official LaserWakefield example cannot be compiled:
I did:

```
pic-create $PIC_EXAMPLES/LaserWakefield myLWFA
cd myLWFA
export PIC_BACKEND="cuda:75" && export OMPI_MCA_io=^ompi
pic-build &> build_log.txt
```
The log file is attached. Do I need to downgrade my gcc, or can the example be adjusted?

Thank you.

[build_log.txt](https://github.com/openPMD/openPMD-viewer/files/13208790/build_log.txt)

**Comment by ax3l** [comment]
Please reopen this issue in https://github.com/ComputationalRadiationPhysics/picongpu @cbontoiu :)
