### ISSUE TITLE
feature: derived fields

### ISSUE THREAD

**Issue by BenWibking** [openPMD/openPMD-viewer#409]
Would it be straightforward to add support to plot derived fields?

That is, could I define a function that operates cell-by-cell on the existing field values in that cell to produce a new field that I could plot in the viewer?

**Comment by RemiLehe** [comment]
Thanks for your interest in `openPMD-viewer`.

I think that, for this use case, I would recommend to do it by hand, i.e. extract the data as `numpy` array with `get_field`/`get_particle`, then apply the function, and then plot it yourself via matplotlib. (The viewer itself is using only simple matplotlib commands under the hood, so plotting via the viewer is not much better than doing it by hand.)
