### ISSUE TITLE
License Headers

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-viewer#56]
We should add a license header to each file stating the 3-Clause-BSD-LBNL license is used.
This is good practice since derivatives might only clone a specific file.

I can prepare a snippet later on, not urgent.

```python
"""
File description 
...

__authors__ = "Remi Lehe, Soeren Jalas, Axel Huebl, ..." (from `git log` of each file)
__copyright__ = "Copyright 2015-2016"
__credits__ = ["Remi Lehe", "Soeren Jalas", "Axel Huebl"]
__license__ = "3-Clause-BSD-LBNL"
"""
```

([addLicense](https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.1.2/src/tools/bin/addLicense) tool in PIConGPU)

Also: avoid UTF-8 for now, write names in pure ascii (sometimes crashes people's setups otherwise)

**Comment by RemiLehe** [comment]
Ok, no problem. Don't hesitate to send a PR for this.
