### ISSUE TITLE
Particle Binning: use actual gridspacing when available

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-viewer#77]
For all kind of particle binning methods (in space, in momentum, ...) it would be very useful to add shape (assignment) functions so one can remove the aliasing noise in the bins.

**Comment by ax3l** [comment]
@RemiLehe did you intentionally change the milestone? I think we can tag `0.1.0` without it and add it later on since it adds completely new functionality (one can still start working on it earlier, but it is not *required* to get `0.1.0` out :) )

**Comment by ax3l** [comment]
An other comment: using the actual grid spacing (spatially) when available for binning *and* adding the correct particle shape are actually two orthogonal tasks.

you might want to split the issue to reflect that :)

**Comment by RemiLehe** [comment]
Regarding the milestone: you are right, we should keep this for 1.0.0 -- especially since I just realized (when trying to implement it) that it will much easier once we have the unit consistency that will be part of 1.0.0

**Comment by RemiLehe** [comment]
Fixed by #132
