### ISSUE TITLE
Consistent module naming: `openpmd_viewer`

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-viewer#82]
For more consistency, the import statement should be changed from `import opmd_viewer` to import `openpmd_viewer`.

In addition:
- The name of the of the folder which contains the source code should ~~also~~ be changed to `openpmd_viewer` (since it's like the *module name*)
- The **name of the package** in `setup.py` should be changed to ~~`openpmd_viewer`~~ `openpmd-viewer` update from @ax3l: see #223

**Comment by RemiLehe** [comment]
I fear that changing the name in setup.py **after** doing a PyPi release will result in two different PyPi packages. Any idea on this @ax3l ?

**Comment by ax3l** [comment]
Don't worry that is not a problem. The changing name I suggested is the *python module* but the *PyPI name* is given in `setup.py` via `name`, `packages`, etc.

A single *PyPI* project can ship several modules and their names do not need to be exactly the same. Therefore it will work as we planned and with `1.0.0` we can unify that the module name is the same as the PyPI name without changing anything in PyPI distribution.

**Comment by ax3l** [comment]
Admittedly, even the `_` is not too great.
See comment in https://github.com/openPMD/openPMD-api/issues/181#issuecomment-390964893

**Comment by ax3l** [comment]
@RemiLehe I changed the title to *module* since the package names have different rules #223 

I suggest the following: proceed with the `import openpmd_viewer` **module name** renaming and let us call the **package** consistently and PEP8-recommended in all channels with a `-` #233

**Comment by ax3l** [comment]
Module name changed for 1.0.0+ in #240
