### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-viewer#90]
We should add a `CHANGES.md` or `CHANGELOG.md` documenting the changes between two releases so users can update their scripts accordingly.

Examples:
 - https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.1.2/CHANGELOG.md
 - https://github.com/ComputationalRadiationPhysics/libSplash/blob/v1.4.0/CHANGELOG.md

**Comment by RemiLehe** [comment]
Do we need a CHANGELOG for version 0.1.0 (the first official release) or should we postpone this to 1.0.0?

**Comment by ax3l** [comment]
Since we added minor incompatibilities we could add a first change log between 9558b0f17d08da055aa99fe988295fad2ba9ec85 (the current `HEAD` of `master` and the `0.1.0`).

**Comment by ax3l** [comment]
closed with #93
