### ISSUE TITLE
Replace the time slider by an iteration slider

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-viewer#92]
Right now the GUI has a time slider, which indicates the time in femtoseconds. 

However, in version 1.0.0 of openPMD-viewer, we are planing to enforce unit consistency and return everything in SI. This means that, for LWFA simulations, the time in the slider will be of the order of 1.e-12.

It turns out that, in this case, the slider does not work anymore! (See for instance: https://github.com/ipython/ipywidgets/issues/259)

Therefore, for version 1.0.0, I am planning to replace the time slider by an iteration slider (which will be more robust to small values of the time). @soerenjalas @ax3l : any objection to this ?

**Comment by ax3l** [comment]
I think having the slider in iteration steps will still work. To get the time in fs, we can just place a label next to it and update it on change with the real time in a format we choose.

**Comment by RemiLehe** [comment]
Closed by #164
