### ISSUE TITLE
User-friendly installation of the package

### ISSUE THREAD

**Issue by RemiLehe** [openPMD/openPMD-viewer#95]
There are several tasks related to the installation that we should go through:
 - Prepare and test installation/uninstallation with `pip`.
 - Prepare and test installation/uninstallation with `conda`.

In particular, we need to add install instructions in the `README` for both `pip` and `conda`. In the case of `pip`, it would be good to distinguish between:
- installation on a cluster  (which requires `module load` instructions for hdf5 parallel)
- installation on a personal computer (which requires that h5py be properly installed, for instance through pip if possible)

**Comment by ax3l** [comment]
small note: for "personal computer" I would recommend `conda` since that can install a serial hdf5 version required for h5py.

on a cluster `pip` or `conda` works equally but MPI, `parallel hdf5` and `parallel h5py` need to be installed [manually](https://gist.github.com/ax3l/928933f0f2cc80eabdd93d64d98827a1#file-warp-hypnos-profile-L83-L86).

**Comment by RemiLehe** [comment]
Actually, now that I think about it, even if `parallel hdf5` is installed on a given plateform, `openPMD-viewer` will actually not use its parallel features, since nowhere in the code did we include MPI-specific code. I am correct?

**Comment by ax3l** [comment]
For *now* ;)

Yes, as long as we have not parallel backend we can simplify things.

**Comment by soerenjalas** [comment]
I agree, but still I think it's best habit to use the provided mpi and hdf5 versions as the codes will need them anyways

**Comment by ax3l** [comment]
yes that is what I am thinking, too. it's also likely that I want to combine them in the same module + virtualenv combination.
