### ISSUE TITLE
`check_all_files=False` breaks slider and time access of data

### ISSUE THREAD

**Issue by soerenjalas** [openPMD/openPMD-viewer#98]
Hi,
in its current implementation `check_all_files=False`, prevents the usage of the slider widget as well as the ability to call `get_field(t=50years...)`. This happens because `self.t` is acquired in the same for loop where the data checking is done:

```python

self.t = np.zeros( N_files )
...
if check_all_files:
            for k in range(1, N_files):
                t, params = read_openPMD_params(self.h5_files[k])
                self.t[k] = t
                for key in params0.keys():
                    if params != params0:
                        print("Warning: File %s has different openPMD "
                              "parameters than the rest of the time series."
                              % self.h5_files[k])
```

This results in a `self.t` array filled with zeros, if `check_all_files=False`.

Sorry for being not too familiar with the standard, but if the timestep is saved within the openPMD file, we could use that in order to determine the time from the iteration data. Otherwise ( if the timestep is not allowed to change, again I need to get more familiar with this stuff) we could only open two files and get the timestep from the difference in time and iteration.

EDIT:
"READ THE FREAKING MANUAL!!"

Turns out this is in fact stated in the standard, but not to the benefit of the problem:
```
dt
type: (float)
description: The latest time step (that was used to reach this iteration). This is needed at the iteration level, since the time step may vary from iteration to iteration in certain codes. 
```

Okay then I see no other way then opening all files to acquire the times.

Technically the api should work without the times so if we want to have a "fast" mode we could have a custom exception thrown whenever a user wants to use the fast mode and call a time argument.  

EDIT 2:
This could be done for example in ` _find_output(self, t, iteration)`

```python
def _find_output(self, t, iteration):
...
        # If a time is requested
        elif (t is not None):
            # NEW
            if self.t == None:
                raise APIError:
                   'Fast-read mode does not support time data acquisition'
            
           # Make sur the time requested does not exceed the allowed bounds
            if t < self.tmin:
                self.current_i = 0
            elif t > self.tmax:
                self.current_i = len(self.t) - 1
...
```

To conclude this, I think that this flag is very nice since checking large datasets can take a great amount of time. Therefore we should try to find an elegant solution to this problem. I also tried to use multiprocessing for the initialisation step, but my attempts failed with the really not so nice implementation of the python multiprocessing module... What are your thoughts on this?

**Comment by RemiLehe** [comment]
Thanks for pointing this out, @soerenjalas.
I agree with your above solution (i.e. raising an exception when the time is not present). I'll do a corresponding pull request. 
Also, I think that now is the right time to replace the time slider by an iteration slider, so that the slider still works even with `check_all_file`.

**Comment by RemiLehe** [comment]
Actually, as discussed on the phone with @soerenjalas, a used a different strategy in PR #100 : the time information is still read, even for `check_all_files = False`. This results is slower reading, but at least the code does not break.
