### ISSUE TITLE
axisLabels not Evaluated

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-viewer#99]
Plotting e.g., 2D fields right now does not add the correct labels to the axis (e.g., they are `x`, `z` as in warp).

For that to change, we just need to read the [`axisLabels` attribute](https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#required-attributes-for-each-mesh-record).

**Comment by RemiLehe** [comment]
Should we close this issue?

**Comment by RemiLehe** [comment]
This was fixed by PR #102
